# Debug notebook for `collect_iterres.py`

This notebook lets you call the script's functions interactively without running it as a CLI script.

**Why a mock `args` is needed:**  
Several functions (`main`, `plot_graphs`) read the module-level `args` variable that is normally
populated by `argparse`. In a notebook `parse_arguments()` would try to parse Jupyter's own
kernel arguments and crash. The cell below injects a fake one instead.

In [1]:
import sys, argparse, os
from paths import scripts_path, data_prod_path, path_to_nn_runs
import numpy as np
import pandas as pd

# ── Point at the directory that contains collect_iterres.py,
#    paths.py, and analysis.py. Adjust as needed. ──────────────────────────
SCRIPT_DIR = scripts_path
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

# ── Build a mock args namespace that mirrors every argparse argument.
#    Tweak the values here to control behaviour, exactly as you would
#    pass flags on the command line. ──────────────────────────────────────
mock_args = argparse.Namespace(
    base_dir        = None,          # will use path_to_nn_runs from paths.py
    out_dir         = "/tmp/debug_out/",
    hk_lookup_path  = None,
    weight_pfi      = False,  # True  → sort by WPFI (PFI × test_accuracy)
                              # False → sort by PFI (or UPS if PFI absent)
    top_kmers       = 500,
    filter_harsh    = False,
    show_cm_bar_percentage = False,
    x_col           = None,
    hue_col         = None,
    group_x_col     = None,
    group_hue_col   = None,
    highlight_multi = False,
    network_top_kmers = 50,
)

nn_run_dir_name = "IterExcl_encoded_sketches_n500_k12"
nn_dir = path_to_nn_runs + nn_run_dir_name + "/"
print("NN directory exists:", os.path.isdir(nn_dir))
if not os.path.isdir(nn_dir):
    raise FileNotFoundError(f"NN directory not found: {nn_dir}")
partition_folder = nn_dir + "cluster_b0_p0_run1/"
print("Partition folder exists:", os.path.isdir(partition_folder))

# ── Import the module and immediately overwrite its global `args`.
#    This must happen before calling any function that references `args`. ──
import collect_iterres as cr
cr.args = mock_args

print("Module loaded. cr.args is now:", cr.args)

NN directory exists: True
Partition folder exists: True

/net/domus/home/people/s215045/miniconda3/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Module loaded. cr.args is now: Namespace(base_dir=None, out_dir='/tmp/debug_out/', hk_lookup_path=None, weight_pfi=False, top_kmers=500, filter_harsh=False, show_cm_bar_percentage=False, x_col=None, hue_col=None, group_x_col=None, group_hue_col=None, highlight_multi=False, network_top_kmers=50)

## Standalone utilities — no `args` dependency

In [ ]:
# ── correct_deci_number ───────────────────────────────────────────────────
# Converts values like 568 → 0.568
print(cr.correct_deci_number(568))   # expect 0.568
print(cr.correct_deci_number(0.75))  # expect 0.75

In [ ]:
# ── calculate_unified_score ───────────────────────────────────────────────
sample_metrics = {
    'test_balanced_accuracy': 0.82,
    'f1': 0.79,
    'unseen_test_balanced_accuracy': 0.71,
}
print("UPS:", cr.calculate_unified_score(sample_metrics))  # expect ~0.763

## Parse a single log file

In [ ]:
# ── extract_metrics_from_log ──────────────────────────────────────────────
LOG_PATH = "/path/to/your/log_run_something.txt"  # <-- change this

result = cr.extract_metrics_from_log(LOG_PATH)
if result:
    metrics, run_info = result
    print("Metrics:", metrics)
    print("Run info:", run_info)
else:
    print("Parsing failed — check the log format.")

## MetricPlottingUtils — plot from a hand-built DataFrame

Useful for testing the plotting code against a small synthetic dataset
without having to scan an entire run directory.

In [ ]:
OUT = "/tmp/debug_out/"
os.makedirs(OUT, exist_ok=True)

# Minimal synthetic run table — add / remove columns to test edge cases
df_test = pd.DataFrame({
    'folder':                    ['run_a', 'run_b', 'run_c'],
    'n':                         [500,     500,     1000   ],
    'k':                         [12,      20,      12     ],
    'test_accuracy':             [0.81,    0.76,    0.84   ],
    'test_balanced_accuracy':    [0.79,    0.73,    0.82   ],
    'unseen_test_accuracy':      [0.70,    0.65,    0.74   ],
    'unseen_test_balanced_accuracy': [0.68, 0.63,   0.72  ],
    'precision':                 [0.80,    0.74,    0.83   ],
    'recall':                    [0.78,    0.72,    0.81   ],
    'f1':                        [0.79,    0.73,    0.82   ],
    'TN':                        [90,      85,      95     ],
    'FN':                        [10,      15,       8     ],
    'FP':                        [ 8,      12,       6     ],
    'TP':                        [92,      88,      97     ],
    'train_pairs':               [1000,    1000,    1200   ],
    'test_pairs':                [200,     200,     240    ],
    'test_train_ratio':          [0.2,     0.2,     0.2    ],
    'status':                    [True,    True,    True   ],
})

plotter = cr.MetricPlottingUtils(df=df_test, outdir=OUT)

# Individual plot helpers (no args dependency)
plotter._plot_bars(
    x_col='n', y_col='test_balanced_accuracy', hue_col='k',
    title='Balanced accuracy by n/k (test)',
    ylabel='Balanced Accuracy',
    outpath=OUT + 'test_balanced_acc.png'
)
print("Plot saved to", OUT + 'test_balanced_acc.png')

In [ ]:
# ── Call plot_graphs() — requires args.show_cm_bar_percentage ─────────────
# mock_args already sets it to False, so this is safe to run as-is.
plotter.plot_graphs()

## GAPlottingUtils — test annotation plots

`GAPlottingUtils` now takes `sort_by` at construction time (`'PFI'`, `'WPFI'`, or `'UPS'`).
This controls both the kmer ordering in the network plot and the y-axis in
`plot_kmer_against_ups_or_pfi`.

In [ ]:
# Build a tiny synthetic annotation dataframe (mirrors what GA.batch_bact_annotate returns)
annot_df = pd.DataFrame({
    'decoded_kmer': ['ATGCGT', 'CCGATG', 'TTACGG', 'ATGCGT', 'GGCAAT'],
    'bact':         ['E.coli', 'E.coli', 'Salmonella', 'Salmonella', 'E.coli'],
    'gene':         ['geneA', 'geneB', 'geneA', 'geneC', 'geneB'],
    'kmer_in_seq':  [5, 3, 7, 2, 4],
    'PFI':          [0.81, 0.74, 0.68, 0.90, 0.55],
    'UPS':          [0.78, 0.70, 0.65, 0.88, 0.52],
})

# sort_by='PFI' matches the default in the updated script
ga_plotter = cr.GAPlottingUtils(df=annot_df, outdir=OUT, sort_by='PFI')

ga_plotter.plot_top_genes(annot_df, entity_type='bacterium', title_suffix='(test)')
ga_plotter.plot_kmer_distribution(annot_df, entity_type='bacterium', title_suffix='(test)')
# plot_kmer_against_ups_or_pfi no longer takes sort_by — it uses self.sort_by
ga_plotter.plot_kmer_against_ups_or_pfi(annot_df, entity_type='bacterium')
print("Gene plots saved.")

## Run main() end-to-end

Reads from a real run directory. Adjust `base_dir` and `out_dir` below.

In [2]:
# Update mock_args if you want different settings for this run
cr.args.top_kmers   = 200
cr.args.weight_pfi  = True
cr.args.filter_harsh = False

cr.main(
    base_dir = nn_dir,
    outdir   = data_prod_path + "TEST/" + nn_run_dir_name+ "/",
    x_col    = None,
    hue_col  = None,
    group_x_col  = None,
    group_hue_col = None,
)

Scanning directory: /net/node07/home/projects/s215045/PredictPhagePPI/nn_runs/IterExcl_encoded_sketches_n500_k12/
Created output directory: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/TEST/IterExcl_encoded_sketches_n500_k12/
[2026-05-23 14:57:18]  collect_iterres started. Scanning /net/node07/home/projects/s215045/PredictPhagePPI/nn_runs/IterExcl_encoded_sketches_n500_k12/ for log files.

Processing folders:   0%|          | 0/36 [00:00<?, ?it/s]

[2026-05-23 14:57:18] Processing folder: cluster_b0_p0_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b0_p0_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b0_p0_run1
Skipping PFI calculation for cluster_b0_p0_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:18] Folder processed: cluster_b0_p0_run1
##################################################

Processing folders:   3%|▎         | 1/36 [00:00<00:05,  6.91it/s]

[2026-05-23 14:57:18] Processing folder: cluster_b0_p1_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b0_p1_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json

Processing folders:   6%|▌         | 2/36 [00:00<00:05,  6.16it/s]

Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b0_p1_run1
Skipping PFI calculation for cluster_b0_p1_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:18] Folder processed: cluster_b0_p1_run1
##################################################

[2026-05-23 14:57:18] Processing folder: cluster_b0_p2_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b0_p2_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b0_p2_run1

Processing folders:   8%|▊         | 3/36 [00:00<00:05,  5.94it/s]

Skipping PFI calculation for cluster_b0_p2_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:18] Folder processed: cluster_b0_p2_run1
##################################################

[2026-05-23 14:57:18] Processing folder: cluster_b0_p3_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b0_p3_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b0_p3_run1
Skipping PFI calculation for cluster_b0_p3_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:18] Folder processed: cluster_b0_p3_run1

Processing folders:  11%|█         | 4/36 [00:00<00:05,  5.85it/s]

##################################################

[2026-05-23 14:57:19] Processing folder: cluster_b0_p5_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b0_p5_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b0_p5_run1
Skipping PFI calculation for cluster_b0_p5_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:19] Folder processed: cluster_b0_p5_run1

Processing folders:  14%|█▍        | 5/36 [00:00<00:05,  5.80it/s]

##################################################

[2026-05-23 14:57:19] Processing folder: cluster_b0_p4_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b0_p4_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b0_p4_run1
Skipping PFI calculation for cluster_b0_p4_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:19] Folder processed: cluster_b0_p4_run1

Processing folders:  17%|█▋        | 6/36 [00:01<00:05,  5.77it/s]

##################################################

[2026-05-23 14:57:19] Processing folder: cluster_b1_p0_run1

Processing folders:  19%|█▉        | 7/36 [00:01<00:05,  5.75it/s]

Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b1_p0_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b1_p0_run1
Skipping PFI calculation for cluster_b1_p0_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:19] Folder processed: cluster_b1_p0_run1
##################################################

[2026-05-23 14:57:19] Processing folder: cluster_b1_p1_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b1_p1_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b1_p1_run1
Skipping PFI calculation for cluster_b1_p1_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:19] Folder processed: cluster_b1_p1_run1
##################################################

Processing folders:  22%|██▏       | 8/36 [00:01<00:05,  5.34it/s]

[2026-05-23 14:57:19] Processing folder: cluster_b1_p2_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b1_p2_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b1_p2_run1

Processing folders:  25%|██▌       | 9/36 [00:01<00:05,  5.23it/s]

Skipping PFI calculation for cluster_b1_p2_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:19] Folder processed: cluster_b1_p2_run1
##################################################

[2026-05-23 14:57:19] Processing folder: cluster_b1_p3_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b1_p3_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b1_p3_run1

Processing folders:  28%|██▊       | 10/36 [00:01<00:05,  4.90it/s]

Skipping PFI calculation for cluster_b1_p3_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:20] Folder processed: cluster_b1_p3_run1
##################################################

[2026-05-23 14:57:20] Processing folder: cluster_b1_p4_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b1_p4_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b1_p4_run1

Processing folders:  31%|███       | 11/36 [00:02<00:05,  4.69it/s]

Skipping PFI calculation for cluster_b1_p4_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:20] Folder processed: cluster_b1_p4_run1
##################################################

[2026-05-23 14:57:20] Processing folder: cluster_b2_p0_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b2_p0_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b2_p0_run1

Processing folders:  33%|███▎      | 12/36 [00:02<00:05,  4.56it/s]

Skipping PFI calculation for cluster_b2_p0_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:20] Folder processed: cluster_b2_p0_run1
##################################################

[2026-05-23 14:57:20] Processing folder: cluster_b1_p5_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b1_p5_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b1_p5_run1

Processing folders:  36%|███▌      | 13/36 [00:02<00:05,  4.47it/s]

Skipping PFI calculation for cluster_b1_p5_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:20] Folder processed: cluster_b1_p5_run1
##################################################

[2026-05-23 14:57:20] Processing folder: cluster_b2_p1_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b2_p1_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b2_p1_run1

Processing folders:  39%|███▉      | 14/36 [00:02<00:04,  4.41it/s]

Skipping PFI calculation for cluster_b2_p1_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:21] Folder processed: cluster_b2_p1_run1
##################################################

[2026-05-23 14:57:21] Processing folder: cluster_b2_p2_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b2_p2_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b2_p2_run1

Processing folders:  42%|████▏     | 15/36 [00:03<00:04,  4.37it/s]

Skipping PFI calculation for cluster_b2_p2_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:21] Folder processed: cluster_b2_p2_run1
##################################################

[2026-05-23 14:57:21] Processing folder: cluster_b2_p3_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b2_p3_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b2_p3_run1

Processing folders:  44%|████▍     | 16/36 [00:03<00:04,  4.35it/s]

Skipping PFI calculation for cluster_b2_p3_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:21] Folder processed: cluster_b2_p3_run1
##################################################

[2026-05-23 14:57:21] Processing folder: cluster_b2_p5_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b2_p5_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b2_p5_run1

Processing folders:  47%|████▋     | 17/36 [00:03<00:04,  4.33it/s]

Skipping PFI calculation for cluster_b2_p5_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:21] Folder processed: cluster_b2_p5_run1
##################################################

[2026-05-23 14:57:21] Processing folder: cluster_b3_p0_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b3_p0_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b3_p0_run1

Processing folders:  50%|█████     | 18/36 [00:03<00:04,  4.31it/s]

Skipping PFI calculation for cluster_b3_p0_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:22] Folder processed: cluster_b3_p0_run1
##################################################

[2026-05-23 14:57:22] Processing folder: cluster_b2_p4_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b2_p4_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b2_p4_run1

Processing folders:  53%|█████▎    | 19/36 [00:03<00:03,  4.31it/s]

Skipping PFI calculation for cluster_b2_p4_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:22] Folder processed: cluster_b2_p4_run1
##################################################

[2026-05-23 14:57:22] Processing folder: cluster_b3_p1_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b3_p1_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b3_p1_run1

Processing folders:  56%|█████▌    | 20/36 [00:04<00:03,  4.30it/s]

Skipping PFI calculation for cluster_b3_p1_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:22] Folder processed: cluster_b3_p1_run1
##################################################

[2026-05-23 14:57:22] Processing folder: cluster_b3_p2_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b3_p2_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b3_p2_run1

Processing folders:  58%|█████▊    | 21/36 [00:04<00:03,  4.29it/s]

Skipping PFI calculation for cluster_b3_p2_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:22] Folder processed: cluster_b3_p2_run1
##################################################

[2026-05-23 14:57:22] Processing folder: cluster_b3_p3_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b3_p3_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b3_p3_run1

Processing folders:  61%|██████    | 22/36 [00:04<00:03,  4.29it/s]

Skipping PFI calculation for cluster_b3_p3_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:22] Folder processed: cluster_b3_p3_run1
##################################################

[2026-05-23 14:57:23] Processing folder: cluster_b3_p4_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b3_p4_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b3_p4_run1

Processing folders:  64%|██████▍   | 23/36 [00:04<00:03,  4.29it/s]

Skipping PFI calculation for cluster_b3_p4_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:23] Folder processed: cluster_b3_p4_run1
##################################################

[2026-05-23 14:57:23] Processing folder: cluster_b4_p0_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b4_p0_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b4_p0_run1

Processing folders:  67%|██████▋   | 24/36 [00:05<00:02,  4.29it/s]

Skipping PFI calculation for cluster_b4_p0_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:23] Folder processed: cluster_b4_p0_run1
##################################################

[2026-05-23 14:57:23] Processing folder: cluster_b3_p5_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b3_p5_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json

Processing folders:  69%|██████▉   | 25/36 [00:05<00:02,  4.29it/s]

Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b3_p5_run1
Skipping PFI calculation for cluster_b3_p5_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:23] Folder processed: cluster_b3_p5_run1
##################################################

[2026-05-23 14:57:23] Processing folder: cluster_b4_p1_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b4_p1_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b4_p1_run1

Processing folders:  72%|███████▏  | 26/36 [00:05<00:02,  4.43it/s]

Skipping PFI calculation for cluster_b4_p1_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:23] Folder processed: cluster_b4_p1_run1
##################################################

[2026-05-23 14:57:23] Processing folder: cluster_b4_p2_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b4_p2_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b4_p2_run1

Processing folders:  75%|███████▌  | 27/36 [00:05<00:02,  4.49it/s]

Skipping PFI calculation for cluster_b4_p2_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:24] Folder processed: cluster_b4_p2_run1
##################################################

[2026-05-23 14:57:24] Processing folder: cluster_b4_p3_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b4_p3_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b4_p3_run1

Processing folders:  78%|███████▊  | 28/36 [00:05<00:01,  4.47it/s]

Skipping PFI calculation for cluster_b4_p3_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:24] Folder processed: cluster_b4_p3_run1
##################################################

[2026-05-23 14:57:24] Processing folder: cluster_b4_p4_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b4_p4_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b4_p4_run1

Processing folders:  81%|████████  | 29/36 [00:06<00:01,  4.46it/s]

Skipping PFI calculation for cluster_b4_p4_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:24] Folder processed: cluster_b4_p4_run1
##################################################

[2026-05-23 14:57:24] Processing folder: cluster_b4_p5_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b4_p5_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b4_p5_run1

Processing folders:  83%|████████▎ | 30/36 [00:06<00:01,  4.41it/s]

Skipping PFI calculation for cluster_b4_p5_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:24] Folder processed: cluster_b4_p5_run1
##################################################

[2026-05-23 14:57:24] Processing folder: cluster_b5_p0_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b5_p0_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b5_p0_run1

Processing folders:  86%|████████▌ | 31/36 [00:06<00:01,  4.37it/s]

Skipping PFI calculation for cluster_b5_p0_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:24] Folder processed: cluster_b5_p0_run1
##################################################

[2026-05-23 14:57:25] Processing folder: cluster_b5_p1_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b5_p1_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b5_p1_run1

Processing folders:  89%|████████▉ | 32/36 [00:06<00:00,  4.39it/s]

Skipping PFI calculation for cluster_b5_p1_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:25] Folder processed: cluster_b5_p1_run1
##################################################

[2026-05-23 14:57:25] Processing folder: cluster_b5_p2_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b5_p2_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b5_p2_run1

Processing folders:  92%|█████████▏| 33/36 [00:07<00:00,  4.36it/s]

Skipping PFI calculation for cluster_b5_p2_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:25] Folder processed: cluster_b5_p2_run1
##################################################

[2026-05-23 14:57:25] Processing folder: cluster_b5_p3_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b5_p3_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b5_p3_run1

Processing folders:  94%|█████████▍| 34/36 [00:07<00:00,  4.53it/s]

Skipping PFI calculation for cluster_b5_p3_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:25] Folder processed: cluster_b5_p3_run1
##################################################

[2026-05-23 14:57:25] Processing folder: cluster_b5_p4_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b5_p4_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b5_p4_run1
Skipping PFI calculation for cluster_b5_p4_run1. Reason: top_kmers=True, hk_lookup=True

Processing folders:  97%|█████████▋| 35/36 [00:07<00:00,  4.46it/s]

[2026-05-23 14:57:25] Folder processed: cluster_b5_p4_run1
##################################################

[2026-05-23 14:57:25] Processing folder: cluster_b5_p5_run1
Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Deduced hk_lookup from log info for cluster_b5_p5_run1 using path: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
Found expected interactions file: top_interaction_pairs_expected_interactions.csv in folder: cluster_b5_p5_run1

Processing folders: 100%|██████████| 36/36 [00:07<00:00,  4.61it/s]

Skipping PFI calculation for cluster_b5_p5_run1. Reason: top_kmers=True, hk_lookup=True

[2026-05-23 14:57:26] Folder processed: cluster_b5_p5_run1
##################################################
Sorted top_kmers_df by weighted PFI score (expected interaction score scaled by test accuracy).
[2026-05-23 14:57:26] Extracted metrics from 36 log files.
Unable to process group_x_col: None, error: 'NoneType' object has no attribute 'lower'. Defaulting to no grouping.
All runs have the same 'n' & 'k' value. Results will be plotted based on rows and not grouped by 'n' and 'k'.
Using x_col: folder, hue_col: None
Dataframe length: 36. Recognized metrics:
  file_path: str
  test_accuracy: float64
  test_balanced_accuracy: float64
  precision: float64
  recall: float64
  f1: float64
  TN: int64
  FN: int64
  FP: int64
  TP: int64
  train_pairs: int64
  test_pairs: int64
  test_train_ratio: float64
  n: int64
  k: int64
  unseen_test_accuracy: float64
  unseen_test_balanced_accuracy: float64
  status: str
  folder: str
  b_value: str
  p_value: str

                                            file_path  test_accuracy  \
0   /net/node07/home/projects/s215045/PredictPhage...         0.8787
1   /net/node07/home/projects/s215045/PredictPhage...         0.8907
2   /net/node07/home/projects/s215045/PredictPhage...         0.8698
3   /net/node07/home/projects/s215045/PredictPhage...         0.8907
4   /net/node07/home/projects/s215045/PredictPhage...         0.9251
5   /net/node07/home/projects/s215045/PredictPhage...         0.8737
6   /net/node07/home/projects/s215045/PredictPhage...         0.8310
7   /net/node07/home/projects/s215045/PredictPhage...         0.9075
8   /net/node07/home/projects/s215045/PredictPhage...         0.8932
9   /net/node07/home/projects/s215045/PredictPhage...         0.9030
10  /net/node07/home/projects/s215045/PredictPhage...         0.8867
11  /net/node07/home/projects/s215045/PredictPhage...         0.8375
12  /net/node07/home/projects/s215045/PredictPhage...         0.9297
13  /net/node07/home/projects/s215045/PredictPhage...         0.8231
14  /net/node07/home/projects/s215045/PredictPhage...         0.8493
15  /net/node07/home/projects/s215045/PredictPhage...         0.8453
16  /net/node07/home/projects/s215045/PredictPhage...         0.8401
17  /net/node07/home/projects/s215045/PredictPhage...         0.8530
18  /net/node07/home/projects/s215045/PredictPhage...         0.8164
19  /net/node07/home/projects/s215045/PredictPhage...         0.8777
20  /net/node07/home/projects/s215045/PredictPhage...         0.8632
21  /net/node07/home/projects/s215045/PredictPhage...         0.8690
22  /net/node07/home/projects/s215045/PredictPhage...         0.8763
23  /net/node07/home/projects/s215045/PredictPhage...         0.8873
24  /net/node07/home/projects/s215045/PredictPhage...         0.8923
25  /net/node07/home/projects/s215045/PredictPhage...         0.9000
26  /net/node07/home/projects/s215045/PredictPhage...         0.9016
27  /net/node07/home/projects/s215045/PredictPhage...         0.9127
28  /net/node07/home/projects/s215045/PredictPhage...         0.8943
29  /net/node07/home/projects/s215045/PredictPhage...         0.9333
30  /net/node07/home/projects/s215045/PredictPhage...         0.9149
31  /net/node07/home/projects/s215045/PredictPhage...         0.9196
32  /net/node07/home/projects/s215045/PredictPhage...         0.9184
33  /net/node07/home/projects/s215045/PredictPhage...         0.9114
34  /net/node07/home/projects/s215045/PredictPhage...         0.9065
35  /net/node07/home/projects/s215045/PredictPhage...         0.9417

    test_balanced_accuracy  precision  recall      f1    TN   FN   FP  TP  \
0                   0.5800     0.0694  0.2632  0.1099   582   14   67   5
1                   0.7201     0.3333  0.5208  0.4065   570   23   50  25
2                   0.6729     0.1786  0.4545  0.2564   566   18   69  15
3                   0.6926     0.2857  0.4651  0.3540   575   23   50  20
4                   0.7973     0.7778  0.6222  0.6914   562   34   16  56
5                   0.5493     0.0893  0.1923  0.1220   493   21   51   5
6                   0.6423     0.1257  0.4340  0.1949   911   30  160  23
7                   0.7912     0.3780  0.6575  0.4800   972   25   79  48
8                   0.6876     0.2632  0.4545  0.3333   974   36   84  30
9                   0.5415     0.1579  0.1286  0.1417  1006   61   48   9
10                  0.6920     0.2328  0.4737  0.3121   904   30   89  27
11                  0.5041     0.1562  0.0490  0.0746   634   97   27   5
12                  0.7220     0.7183  0.4636  0.5635   994   59   20  51
13                  0.5203     0.2500  0.0870  0.1290   618  105   30  10
14                  0.5429     0.5000  0.1043  0.1727   636  103   12  12
15                  0.5040     0.1875  0.0278  0.0484   642  105   13   3
16                  0.5430     0.7500  0.0923  0.1644   629  118    4  12
17                  0.5112     0.0500  0.1379  0.0734   582   25   76   4
18                  0.5393     0.3333  0.1284  0.1854   533   95   28  14
19                  0.6541     0.3099  0.3860  0.3438   581   35   49  22
20                  0.5932     0.1579  0.2857  0.2034   581   30   64  12
21                  0.6351     0.2533  0.3585  0.2969   578   34   56  19
22                  0.5186     0.0889  0.1111  0.0988   513   32   41   4
23                  0.8724     0.0789  0.8571  0.1446   553    1   70   6
24                  0.7047     0.6825  0.4433  0.5375   570   54   20  43
25                  0.8202     0.3375  0.7297  0.4615   540   10   53  27
26                  0.7688     0.2206  0.6250  0.3261   553    9   53  15
27                  0.6329     0.2273  0.3226  0.2667   565   21   34  10
28                  0.6678     0.1111  0.4286  0.1765   468    8   48   6
29                  0.7934     0.8305  0.6049  0.7000   539   32   10  49
30                  0.5964     0.0781  0.2632  0.1205   780   14   59   5
31                  0.7369     0.3611  0.5306  0.4298   763   23   46  26
32                  0.6473     0.2000  0.3529  0.2553   776   22   48  12
33                  0.7168     0.2895  0.5000  0.3667   760   22   54  22
34                  0.5769     0.0833  0.2273  0.1220   693   17   55   5
35                  0.7689     0.8475  0.5495  0.6667   758   41    9  50

    ...  test_pairs  test_train_ratio    n   k  unseen_test_accuracy  \
0   ...         668            0.3588  500  12                0.9792
1   ...         668            0.3588  500  12                0.9583
2   ...         668            0.3588  500  12                0.9167
3   ...         668            0.3588  500  12                0.9792
4   ...         668            0.3588  500  12                0.9167
5   ...         570            0.2908  500  12                0.9722
6   ...        1124            0.7994  500  12                0.9097
7   ...        1124            0.7994  500  12                0.7153
8   ...        1124            0.7994  500  12                0.6528
9   ...        1124            0.7994  500  12                0.6944
10  ...        1050            0.7095  500  12                0.8889
11  ...         763            0.4318  500  12                0.9706
12  ...        1124            0.7994  500  12                0.6667
13  ...         763            0.4318  500  12                0.7206
14  ...         763            0.4318  500  12                0.9118
15  ...         763            0.4318  500  12                0.7059
16  ...         763            0.4318  500  12                0.2941
17  ...         687            0.3728  500  12                0.0385
18  ...         670            0.3602  500  12                0.9608
19  ...         687            0.3728  500  12                0.0769
20  ...         687            0.3728  500  12                0.1154
21  ...         687            0.3728  500  12                0.0577
22  ...         590            0.3041  500  12                0.1282
23  ...         630            0.3316  500  12                1.0000
24  ...         687            0.3728  500  12                0.3269
25  ...         630            0.3316  500  12                1.0000
26  ...         630            0.3316  500  12                1.0000
27  ...         630            0.3316  500  12                1.0000
28  ...         530            0.2650  500  12                1.0000
29  ...         630            0.3316  500  12                1.0000
30  ...         858            0.5132  500  12                0.9886
31  ...         858            0.5132  500  12                0.9886
32  ...         858            0.5132  500  12                0.9659
33  ...         858            0.5132  500  12                1.0000
34  ...         770            0.4375  500  12                0.9242
35  ...         858            0.5132  500  12                0.9659

    unseen_test_balanced_accuracy  status         folder b_value p_value
0                          0.5000  passed  cluster_b0_p0       0       0
1                          0.5000  passed  cluster_b0_p1       0       1
2                          0.5000  passed  cluster_b0_p2       0       2
3                          0.5000  passed  cluster_b0_p3       0       3
4                          0.5000  passed  cluster_b0_p5       0       5
5                          0.5000  passed  cluster_b0_p4       0       4
6                          0.4580  passed  cluster_b1_p0       1       0
7                          0.7208  passed  cluster_b1_p1       1       1
8                          0.3381  passed  cluster_b1_p2       1       2
9                          0.4853  passed  cluster_b1_p3       1       3
10                         0.4615  passed  cluster_b1_p4       1       4
11                         0.5000  passed  cluster_b2_p0       2       0
12                         0.5476  passed  cluster_b1_p5       1       5
13                         0.5000  passed  cluster_b2_p1       2       1
14                         0.5000  passed  cluster_b2_p2       2       2
15                         0.5000  passed  cluster_b2_p3       2       3
16                         0.5000  passed  cluster_b2_p5       2       5
17                         0.5000  passed  cluster_b3_p0       3       0
18                         0.5000  passed  cluster_b2_p4       2       4
19                         0.5000  passed  cluster_b3_p1       3       1
20                         0.5000  passed  cluster_b3_p2       3       2
21                         0.5100  passed  cluster_b3_p3       3       3
22                         0.5405  passed  cluster_b3_p4       3       4
23                         1.0000  passed  cluster_b4_p0       4       0
24                         0.5511  passed  cluster_b3_p5       3       5
25                         1.0000  passed  cluster_b4_p1       4       1
26                         1.0000  passed  cluster_b4_p2       4       2
27                         1.0000  passed  cluster_b4_p3       4       3
28                         1.0000  passed  cluster_b4_p4       4       4
29                         1.0000  passed  cluster_b4_p5       4       5
30                         0.5000  passed  cluster_b5_p0       5       0
31                         0.5000  passed  cluster_b5_p1       5       1
32                         0.5000  passed  cluster_b5_p2       5       2
33                         1.0000  passed  cluster_b5_p3       5       3
34                         0.5000  passed  cluster_b5_p4       5       4
35                         0.5000  passed  cluster_b5_p5       5       5

[36 rows x 21 columns]
✓ Summary CSVs saved as all_runs_summary.csv and top_kmers_summary.csv
[2026-05-23 14:57:26] Extracted top k-mers from 36 files.
Bacterium k-mers sample:
                   hash  entity   organism  decoded_kmer       PFI     UPS  \
2400  60472713233729507  J99_22  bacterium  ATCACCTCTGTA  0.002186  0.6039
2402  60472713233729507  J99_22  bacterium  CGTGTGTGTATC  0.002172  0.6039
2401  60472713233729507  J99_22  bacterium  CAAACGGGGTGA  0.002172  0.6039
2403  60472713233729507  J99_22  bacterium  CTTTACCTTACT  0.002131  0.6039
2404  60472713233729507  J99_22  bacterium  CCTACGCCGTAT  0.002131  0.6039

      test_accuracy              folder      WPFI
2400         0.9297  cluster_b1_p5_run1  0.002033
2402         0.9297  cluster_b1_p5_run1  0.002020
2401         0.9297  cluster_b1_p5_run1  0.002020
2403         0.9297  cluster_b1_p5_run1  0.001981
2404         0.9297  cluster_b1_p5_run1  0.001981
Phage k-mers sample:
                  hash   entity organism  decoded_kmer       PFI     UPS  \
2400   950261943178681  Poppous    phage  ATACCGTAAGCC  0.002186  0.6039
2402  1013288893183793  Poppous    phage  ATACCGTAAGCC  0.002172  0.6039
2401   671839161750206  Poppous    phage  ATACCGTAAGCC  0.002172  0.6039
2403  1452759213318643  Poppous    phage  ATACCGTAAGCC  0.002131  0.6039
2404  1804634374934716  Poppous    phage  ATACCGTAAGCC  0.002131  0.6039

      test_accuracy              folder      WPFI
2400         0.9297  cluster_b1_p5_run1  0.002033
2402         0.9297  cluster_b1_p5_run1  0.002020
2401         0.9297  cluster_b1_p5_run1  0.002020
2403         0.9297  cluster_b1_p5_run1  0.001981
2404         0.9297  cluster_b1_p5_run1  0.001981
Top k-mers with WPFI scores - bacterium:
      entity  decoded_kmer      WPFI
2400  J99_22  ATCACCTCTGTA  0.002033
2402  J99_22  CGTGTGTGTATC  0.002020
2401  J99_22  CAAACGGGGTGA  0.002020
2403  J99_22  CTTTACCTTACT  0.001981
2404  J99_22  CCTACGCCGTAT  0.001981
Top k-mers with WPFI scores - phage:
       entity  decoded_kmer      WPFI
2400  Poppous  ATACCGTAAGCC  0.002033
2402  Poppous  ATACCGTAAGCC  0.002020
2401  Poppous  ATACCGTAAGCC  0.002020
2403  Poppous  ATACCGTAAGCC  0.001981
2404  Poppous  ATACCGTAAGCC  0.001981
Reduced bacterium k-mers from 7200 to 200 based on top_kmers and sorting criteria.
Reduced phage k-mers from 7200 to 200 based on top_kmers and sorting criteria.
Final bacterium sample:
                   hash  entity   organism  decoded_kmer       PFI     UPS  \
2400  60472713233729507  J99_22  bacterium  ATCACCTCTGTA  0.002186  0.6039
2402  60472713233729507  J99_22  bacterium  CGTGTGTGTATC  0.002172  0.6039
2401  60472713233729507  J99_22  bacterium  CAAACGGGGTGA  0.002172  0.6039
2403  60472713233729507  J99_22  bacterium  CTTTACCTTACT  0.002131  0.6039
2404  60472713233729507  J99_22  bacterium  CCTACGCCGTAT  0.002131  0.6039

      test_accuracy              folder      WPFI
2400         0.9297  cluster_b1_p5_run1  0.002033
2402         0.9297  cluster_b1_p5_run1  0.002020
2401         0.9297  cluster_b1_p5_run1  0.002020
2403         0.9297  cluster_b1_p5_run1  0.001981
2404         0.9297  cluster_b1_p5_run1  0.001981
Final phage sample:
                  hash   entity organism  decoded_kmer       PFI     UPS  \
2400   950261943178681  Poppous    phage  ATACCGTAAGCC  0.002186  0.6039
2402  1013288893183793  Poppous    phage  ATACCGTAAGCC  0.002172  0.6039
2401   671839161750206  Poppous    phage  ATACCGTAAGCC  0.002172  0.6039
2403  1452759213318643  Poppous    phage  ATACCGTAAGCC  0.002131  0.6039
2404  1804634374934716  Poppous    phage  ATACCGTAAGCC  0.002131  0.6039

      test_accuracy              folder      WPFI
2400         0.9297  cluster_b1_p5_run1  0.002033
2402         0.9297  cluster_b1_p5_run1  0.002020
2401         0.9297  cluster_b1_p5_run1  0.002020
2403         0.9297  cluster_b1_p5_run1  0.001981
2404         0.9297  cluster_b1_p5_run1  0.001981

Annotating bacteria-kmer pairs: 100%|██████████| 200/200 [00:33<00:00,  6.01it/s]
Annotating phage-kmer pairs: 100%|██████████| 200/200 [00:26<00:00,  7.64it/s]

[2026-05-23 14:58:26] Script execution completed.

---
## Per-partition GAPlottingUtils

The cells below run the full annotation + GAPlottingUtils pipeline on **each partition folder
individually**, rather than pooling everything together as `main()` does.

Each partition gets its own subdirectory under `BASE_OUT` so the plots never overwrite each other.

**Pipeline per folder:**
1. Parse the log file → extract metrics + run_info
2. Calculate UPS from those metrics; attach `UPS` and `test_accuracy` to `df_kmers`
3. Load `pair_kmers.csv`; rename `expected_interaction_score` → `PFI` if present
4. Optionally compute `WPFI = PFI × test_accuracy` (mirrors `weight_pfi` flag)
5. Resolve `sort_by`: `WPFI` → `PFI` → `UPS` (same priority as `main()`)
6. Split into `bact_df` / `phage_df` using the `bact_*` / `phage_*` column prefixes
   and extract `hash` from the `pair` column — matching the updated split logic in the script
7. Subset to top-k kmers via `balanced_top_k`
8. Annotate with `GeneAnalysis`
9. Instantiate `GAPlottingUtils(sort_by=sort_by)` and run all plot methods

In [7]:
def resolve_sort_by(df_kmers: pd.DataFrame, weight_pfi: bool) -> tuple:
    """
    Determine the score column and title suffix to use for sorting,
    following the same priority logic as main():
      weight_pfi=True  → WPFI (PFI × test_accuracy) if possible, else PFI
      weight_pfi=False → PFI if present, else UPS

    Returns (sort_by: str, title_suffix: str, df_kmers: pd.DataFrame)
    with WPFI column added to df_kmers when applicable.
    """
    # Normalise column name produced by older runs
    if 'expected_interaction_score' in df_kmers.columns and 'PFI' not in df_kmers.columns:
        df_kmers = df_kmers.rename(columns={'expected_interaction_score': 'PFI'})

    if 'PFI' in df_kmers.columns:
        if weight_pfi:
            if 'test_accuracy' in df_kmers.columns:
                df_kmers['WPFI'] = df_kmers['PFI'] * df_kmers['test_accuracy']
                return 'WPFI', '(WPFI)', df_kmers
            else:
                print("Warning: 'test_accuracy' missing — cannot weight PFI. Falling back to PFI.")
        return 'PFI', '(PFI)', df_kmers

    return 'UPS', '(UPS)', df_kmers


def split_bact_phage(df_kmers: pd.DataFrame) -> tuple:
    """
    Split a pair_kmers DataFrame into bact_df and phage_df using the
    bact_* / phage_* column prefixes and hash extraction from `pair`,
    exactly as main() does in the updated script.

    Score columns (PFI, UPS, test_accuracy, WPFI) are carried through
    whichever are present.

    Returns (bact_df, phage_df).
    """
    score_cols = [c for c in ('PFI', 'UPS', 'test_accuracy', 'WPFI') if c in df_kmers.columns]
    base_cols  = score_cols + ['folder']

    # ── Bacterium ─────────────────────────────────────────────────────────
    bact_df = df_kmers[['bact_entity', 'bact_organism', 'bact_decoded_kmer'] + base_cols].copy()
    bact_df = bact_df.rename(columns={
        'bact_entity':      'entity',
        'bact_organism':    'organism',
        'bact_decoded_kmer':'decoded_kmer',
    })
    if 'pair' in df_kmers.columns:
        try:
            bact_df.insert(0, 'hash',
                df_kmers['pair'].str.extract(r'np\.int64\((\d+)\)')[0].astype('int64'))
        except Exception as e:
            print(f"Could not extract bact hash from 'pair' column: {e}")

    # ── Phage ─────────────────────────────────────────────────────────────
    phage_df = df_kmers[['phage_entity', 'phage_organism', 'phage_decoded_kmer'] + base_cols].copy()
    phage_df = phage_df.rename(columns={
        'phage_entity':      'entity',
        'phage_organism':    'organism',
        'phage_decoded_kmer':'decoded_kmer',
    })
    if 'pair' in df_kmers.columns:
        try:
            phage_df.insert(0, 'hash',
                df_kmers['pair'].str.extract(r'np\.int64\(\d+\).*?np\.int64\((\d+)\)')[0].astype('int64'))
        except Exception as e:
            print(f"Could not extract phage hash from 'pair' column: {e}")

    return bact_df, phage_df


def plot_partition(folder_path, folder_name, base_out,
                   top_kmers=500, network_top_kmers=50,
                   hk_lookup_path=None, weight_pfi=False):
    """
    Run GAPlottingUtils plots for a single partition folder.

    Parameters
    ----------
    folder_path      : str  – absolute path to the partition directory
    folder_name      : str  – name used for plot titles and the output subdirectory
    base_out         : str  – root output dir; a per-partition subfolder is created inside it
    top_kmers        : int  – passed to balanced_top_k
    network_top_kmers: int  – passed to plot_kmer_gene_network
    hk_lookup_path   : str  – explicit path to a hk_lookup JSON; None → deduced from run_info
    weight_pfi       : bool – mirrors the --weight_pfi CLI flag:
                              True  → sort by WPFI (PFI × test_accuracy)
                              False → sort by PFI if available, else UPS

    Returns
    -------
    dict with keys 'bact', 'phage' (annotated DataFrames), 'metrics', 'ups', 'sort_by'
    or None if the folder could not be processed.
    """
    outdir = os.path.join(base_out, folder_name, "")
    os.makedirs(outdir, exist_ok=True)

    # ── 1. Parse log file ─────────────────────────────────────────────────
    metrics, run_info = None, None
    for fname in os.listdir(folder_path):
        if fname.endswith(".txt") and "log_run" in fname.lower():
            result = cr.extract_metrics_from_log(os.path.join(folder_path, fname))
            if result:
                metrics, run_info = result
                break

    if metrics is None:
        print(f"[{folder_name}] No parseable log file — skipping.")
        return None

    # ── 2. UPS and test_accuracy (attached per-row, same as main()) ───────
    ups           = cr.calculate_unified_score(metrics)
    test_accuracy = metrics.get('test_accuracy', None)

    # ── 3. Load expected_interactions.csv ─────────────────────────────────
    kmers_path = None
    for fname in os.listdir(folder_path):
        if fname.endswith("expected_interactions.csv"):
            kmers_path = os.path.join(folder_path, fname)
            break

    if kmers_path is None:
        print(f"[{folder_name}] No expected_interactions.csv — skipping.")
        return None

    df_kmers = pd.read_csv(kmers_path)
    df_kmers['folder']        = folder_name
    df_kmers['UPS']           = ups
    df_kmers['test_accuracy'] = test_accuracy

    # ── 4. Resolve hk_lookup ─────────────────────────────────────────────
    if hk_lookup_path:
        cr.open_hk_lookup(hk_lookup_path, reverse=True)   # side-effect: cached in cr
    elif run_info:
        try:
            dir_name = "encoded_sketches" if run_info.get('use_encoded') else "SM_sketches"
            if run_info.get('data2'):
                dir_name += "_data2"
            hk_path = os.path.join(
                cr.data_prod_path, dir_name,
                f"hk_lookup_n{metrics['n']}_k{metrics['k']}.json"
            )
            cr.open_hk_lookup(hk_path, reverse=True)
        except Exception as e:
            print(f"[{folder_name}] Could not resolve hk_lookup: {e}")

    # ── 5. Determine score column (WPFI / PFI / UPS) ─────────────────────
    sort_by, title_suffix, df_kmers = resolve_sort_by(df_kmers, weight_pfi=weight_pfi)
    print(f"[{folder_name}] Sorting by '{sort_by}'")

    # ── 6. Split into bact_df / phage_df (updated column-prefix logic) ───
    required_bact_cols  = {'bact_entity', 'bact_organism', 'bact_decoded_kmer'}
    required_phage_cols = {'phage_entity', 'phage_organism', 'phage_decoded_kmer'}

    if not required_bact_cols.issubset(df_kmers.columns) and \
       not required_phage_cols.issubset(df_kmers.columns):
        print(f"[{folder_name}] pair_kmers.csv is missing bact_*/phage_* columns — skipping.")
        return None

    bact_df, phage_df = split_bact_phage(df_kmers)

    # ── 7. Subset to top_kmers per entity ────────────────────────────────
    if not bact_df.empty and sort_by in bact_df.columns:
        bact_df = cr.balanced_top_k(
            bact_df, group_cols=['entity'], sort_col=sort_by, total_k=top_kmers
        )
    if not phage_df.empty and sort_by in phage_df.columns:
        phage_df = cr.balanced_top_k(
            phage_df, group_cols=['entity'], sort_col=sort_by, total_k=top_kmers
        )

    # ── 8. Annotate ───────────────────────────────────────────────────────
    GA = cr.GeneAnalysis()
    bact_annot  = pd.DataFrame()
    phage_annot = pd.DataFrame()

    if not bact_df.empty:
        try:
            # bact_annot = GA.batch_bact_annotate(
            #     bkmers     = bact_df['decoded_kmer'].tolist(),
            #     bact_names = bact_df['entity'].tolist(),
            #     data_prod_path = cr.data_prod_path,
            # )
            bact_annot = GA.batch_bact_annotate(
                bact_df=bact_df, 
                kmer_col='decoded_kmer', 
                entity_col='entity', 
                data_prod_path=data_prod_path
            )
            print(f"[{folder_name}] Bacterium annotation: {len(bact_annot)} rows")
        except Exception as e:
            print(f"[{folder_name}] Bacterium annotation failed: {e}")

    if not phage_df.empty:
        try:
            phage_annot = GA.batch_phage_annotate(
                phage_df=phage_df, 
                kmer_col='decoded_kmer', 
                entity_col='entity', 
                data_prod_path=data_prod_path
            )
            print(f"[{folder_name}] Phage annotation: {len(phage_annot)} rows")
        except Exception as e:
            print(f"[{folder_name}] Phage annotation failed: {e}")

    # ── 9. Plot ───────────────────────────────────────────────────────────
    # GAPlottingUtils now receives sort_by at construction time
    ga_plotter = cr.GAPlottingUtils(df=df_kmers, outdir=outdir, sort_by=sort_by)
    bact_df_agg = bact_annot.groupby("gene")["kmer_in_seq"].agg(lambda x: ';'.join(sorted(set([str(v) for v in x if pd.notna(v)])))).reset_index()
    display(bact_df_agg)
    display(bact_annot)

    if not bact_annot.empty:
        ga_plotter.plot_top_genes(
            bact_annot, entity_type='bacterium', title_suffix=f'{title_suffix} ({folder_name})')
        ga_plotter.plot_kmer_distribution(
            bact_annot, entity_type='bacterium', title_suffix=f'{title_suffix} ({folder_name})')
        ga_plotter.plot_kmer_gene_network(
            bact_annot, entity_type='bacterium', top_kmers=network_top_kmers)
        # plot_kmer_against_ups_or_pfi uses self.sort_by — no argument needed
        ga_plotter.plot_kmer_against_ups_or_pfi(bact_annot, entity_type='bacterium')

    if not phage_annot.empty:
        ga_plotter.plot_top_genes(
            phage_annot, entity_type='phage', title_suffix=f'{title_suffix} ({folder_name})')
        ga_plotter.plot_kmer_distribution(
            phage_annot, entity_type='phage', title_suffix=f'{title_suffix} ({folder_name})')
        ga_plotter.plot_kmer_gene_network(
            phage_annot, entity_type='phage', top_kmers=network_top_kmers)
        ga_plotter.plot_kmer_against_ups_or_pfi(phage_annot, entity_type='phage')

    if bact_annot.empty and phage_annot.empty:
        print(f"[{folder_name}] Both annotation DataFrames empty — no plots generated.")
    else:
        print(f"[{folder_name}] Plots saved to: {outdir}")

    return {
        'bact':    bact_annot,
        'phage':   phage_annot,
        'metrics': metrics,
        'ups':     ups,
        'sort_by': sort_by,
    }

In [ ]:
# ── Configure and run the per-partition loop ──────────────────────────────
BASE_DIR = nn_dir
BASE_OUT = data_prod_path + "TEST/" + nn_run_dir_name + "/"

# Optional: restrict to a subset of folders for a quick test
# ONLY_FOLDERS = {'cluster_1_PhageA', 'cluster_2_PhageB'}  # set to None to process all
ONLY_FOLDERS = {"cluster_b0_p0_run1"}

TOP_KMERS         = 200
NETWORK_TOP_KMERS = 50
HK_LOOKUP_PATH    = None   # or a path string to override auto-deduction
WEIGHT_PFI        = False  # set True to sort by WPFI instead of PFI

partition_results = {}

for folder_name in sorted(os.listdir(BASE_DIR)):
    if ONLY_FOLDERS and folder_name not in ONLY_FOLDERS:
        continue
    folder_path = os.path.join(BASE_DIR, folder_name)
    if not os.path.isdir(folder_path):
        continue

    partition_results[folder_name] = plot_partition(
        folder_path       = folder_path,
        folder_name       = folder_name,
        base_out          = BASE_OUT,
        top_kmers         = TOP_KMERS,
        network_top_kmers = NETWORK_TOP_KMERS,
        hk_lookup_path    = HK_LOOKUP_PATH,
        weight_pfi        = WEIGHT_PFI,
    )

succeeded = [k for k, v in partition_results.items() if v is not None]
print(f"\nDone. {len(succeeded)}/{len(partition_results)} partitions processed successfully.")

Loaded hk_lookup JSON file from /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/encoded_sketches/hk_lookup_n500_k12.json
[cluster_b0_p0_run1] Sorting by 'PFI'

Annotating bacteria-kmer pairs: 100%|██████████| 50/50 [00:08<00:00,  5.78it/s]

[cluster_b0_p0_run1] Bacterium annotation: 16 rows

Annotating phage-kmer pairs: 100%|██████████| 50/50 [00:06<00:00,  7.28it/s]

[cluster_b0_p0_run1] Phage annotation: 0 rows

   gene   kmer_in_seq
0  patZ  CGCTGCAGAATG

,bact,locus_tag,kmer_in_seq,length_bp,gene,product,UPS,PFI
0,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
1,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358
2,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
3,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358
4,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
5,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358
6,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
7,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358
8,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
9,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358
10,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
11,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358
12,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
13,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358
14,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
15,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358

Ordering kmers by PFI (descending, aggregated by mean).
[cluster_b0_p0_run1] Plots saved to: /net/node07/home/projects/s215045/PredictPhagePPI/data_prod/TEST/IterExcl_encoded_sketches_n500_k12/cluster_b0_p0_run1/

Done. 1/1 partitions processed successfully.

In [8]:
# ── Inspect results for a single partition without re-running ─────────────
# Change the name below to any key from partition_results.
INSPECT = succeeded[0] if succeeded else None

if INSPECT:
    r = partition_results[INSPECT]
    print(f"=== {INSPECT} ===")
    print(f"UPS:     {r['ups']}")
    print(f"sort_by: {r['sort_by']}")
    print(f"Metrics: {r['metrics']}\n")

    if not r['bact'].empty:
        print("Bacterium annotation (head):")
        display(r['bact'].head())

    if not r['phage'].empty:
        print("Phage annotation (head):")
        display(r['phage'].head())
else:
    print("No successful partitions to inspect.")

=== cluster_b0_p0_run1 ===
UPS:     0.4265
sort_by: PFI
Metrics: {'file_path': '/net/node07/home/projects/s215045/PredictPhagePPI/nn_runs/IterExcl_encoded_sketches_n500_k12/cluster_b0_p0_run1/log_run1.txt', 'test_accuracy': 0.8787, 'test_balanced_accuracy': 0.58, 'precision': 0.0694, 'recall': 0.2632, 'f1': 0.1099, 'TN': 582, 'FN': 14, 'FP': 67, 'TP': 5, 'train_pairs': 1862, 'test_pairs': 668, 'test_train_ratio': 0.3588, 'n': 500, 'k': 12, 'unseen_test_accuracy': 0.9792, 'unseen_test_balanced_accuracy': 0.5, 'status': True}

Bacterium annotation (head):

,bact,locus_tag,kmer_in_seq,length_bp,gene,product,UPS,PFI
0,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
1,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358
2,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358
3,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,Peptidyl-lysine N-acetyltransferase PatZ,0.4265,0.000358
4,J99_22,KCDMCKIA_03467,CGCTGCAGAATG,2652,patZ,NaN,0.4265,0.000358

In [9]:
# ── Quick score summary across all partitions ─────────────────────────────
summary = pd.DataFrame([
    {
        'partition': k,
        'sort_by':   v['sort_by'],
        'ups':       v['ups'],
        **{m: v['metrics'].get(m) for m in
           ['test_balanced_accuracy', 'unseen_test_balanced_accuracy', 'f1']}
    }
    for k, v in partition_results.items() if v is not None
]).sort_values('ups', ascending=False)

display(summary)

,partition,sort_by,ups,test_balanced_accuracy,unseen_test_balanced_accuracy,f1
0,cluster_b0_p0_run1,PFI,0.4265,0.58,0.5,0.1099